try {
//   console.log(x);
// } catch (error) {
//   console.log("ReferenceError :", error.message);
// }